
--CREATE A NEW DATABASE

CREATE DATABASE DBS   --<<  PRIMARY SOURCE PRODUCTION DATABASE
GO

--CREATE TABLE NAMES

USE DBS
GO

CREATE TABLE NAMES (id INT, FNAME VARCHAR (20))

--INSERT DATA INTO TABLE

INSERT INTO NAMES VALUES (1,'ALBERT'),(2,'BOB'),(3,'CHARLES')

--VIEW DATA

SELECT * FROM NAMES

--VEIW ALL DATABASES, INCLUDING THE DBS

Select * from sys.databases

--VIEW THE LOGICAL NAME OF THE DATA FILE OF PRODUCTION DBS

Sp_helpdb 'DBS'


--CREATE A DATABASE SNAPSHOT OF DBS

CREATE DATABASE Snapshot_DBS ON          --<< NAME OF THE SNAPSHOT DB
(Name ='DBS',                            --<< NAME OF THE LOGICAL DATA FILE
FileName='C:\Snapshots\Snapshot_DBS.ss') --<< FILE LOCATION OF THE SNAPSHOT WITH SS EXTENTION
AS SNAPSHOT OF DBS;
GO

--REVIEW THE SIZE OF DATABASE VIA GUI

--DROP TABLE ON PRIMARY PRODUCTION DATABASE DBS

USE DBS
GO

DROP TABLE NAMES

--RESTORE THE TABLE FROM THE SNAPSHOT

USE MASTER
GO

RESTORE DATABASE DBS
FROM DATABASE_SNAPSHOT = 'Snapshot_DBS'

--VERIFY RECOVERY OF TABLE

USE DBS
GO

SELECT * FROM NAMES

--INSERT NEW DATA INTO PRODUCTION DATABASE AND TABLE

USE DBS
GO

INSERT INTO NAMES VALUES (4,'EUGENE')

USE DBS
GO

SELECT * FROM NAMES

--DID IT UPDATE THE SNAPSHOT DATABASE AND TABLE??

USE Snapshot_DBS
GO

SELECT * FROM NAMES

--NO!!! AS THE SNAPSHOT IS ONLY CONTAINS A THE 'COPY' AT THE TIME OF THE SNAPSHOT CREATION

--CAN YOU EXECUTE UPDATE OR INSERT THE SNAPSHOT TABLE(S)?

USE Snapshot_DBS
GO

UPDATE NAMES
SET FNAME = 'It Dept'

--CANOT UPDATE OR INSERT OR DELETE AS IT'S READ-ONLY


DROP DATABASE Snapshot_DBS
GO

